# ldp-identity-api.values.yaml

replicaCount: 1

image:
  repository: alanbruhns/ldpidentityapi
  tag: "latest"  # This will be updated dynamically by the GitHub Actions pipeline
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: identity.ldp.alanbruhns.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-secret
      hosts:
        - identity.ldp.alanbruhns.io

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Production
