imagePullSecrets: 
  - name: "docker-hub-secret"

image:
  repository: docker.io/alanbruhns/ldp-api-hi
  tag: 1.0.4

service:
  type: ClusterIP
  port: 8080
  
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /readyz
    port: http
    