imagePullSecrets: 
  - name: "docker-hub-secret"

image:
  repository: docker.io/alanbruhns/ldp-api-identity
  tag: 1.0.6

service:
  type: ClusterIP
  port: 80
  
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /readyz
    port: http
    
ingress:
  enabled: true
  className: ""
  annotations: {}
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ldp-identity-api.develop.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []