imagePullSecrets: 
  - name: "docker-hub-secret"

image:
  repository: docker.io/alanbruhns/ldp-api-identity
  tag: develop

service:
  type: ClusterIP
  port: 80
  
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /readyz
    port: http
    